upstream flask_app {
    server flaskapp1:8000;
    server flaskapp2:8000;
}

server {
    listen 80;
    location / {
        proxy_pass http://flask_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}